import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/app/components/simple/Header";
import Banner from "@/app/components/simple/BannerPage/Banner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "PORTFOLIO | Schegoleva Yulya",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${geistSans.variable} ${geistMono.variable} 
        antialiased container pt-8 flex flex-col`}>
      <Header className={'self-center pb-16'}/>
      <Banner className={'pb-8'}/>
        {children}
      </body>
    </html>
  );
}
